services:
  jupyter-notebook:
    image:  gur5/heart-failure-prediction:32328d6
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
