name: heart_failure_analysis_project
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - altair
  - vega_datasets
  - scikit-learn
  - imbalanced-learn
  - scipy
  - pillow
  - jinja2
  - joblib
  - pip
  - ipykernel
  - nb_conda_kernels

